<?php
error_reporting(E_ALL);
ini_set('display_errors', 0); // Keep 0 for production, set to 1 if you are still debugging
header('Content-Type: application/json');
session_start();
require_once '../../config/database.php';

// Get the POST data
$json = file_get_contents('php://input');
$data = json_decode($json, true);

if (!$data) {
    echo json_encode(['success' => false, 'error' => 'Invalid JSON input received by server']);
    exit;
}

/** 
 * DATA EXTRACTION
 * We try to get user_id from session first for security, 
 * but fall back to the JSON payload for your current testing.
 */
$user_id    = $_SESSION['user_id'] ?? $data['user_id'] ?? null;
$product_id = $data['product_id'] ?? null;
$quantity   = $data['quantity']   ?? 1;
$unit_price = $data['unit_price'] ?? 0;
$slot_id    = $data['slot_id']    ?? null;
$amount     = round($quantity * $unit_price, 2);

// --- IMPROVED VALIDATION ---
// This tells you exactly WHAT is missing in the console
$missing = [];
if (!$user_id)    $missing[] = 'user_id';
if (!$product_id) $missing[] = 'product_id';
if (!$slot_id)    $missing[] = 'slot_id';

if (!empty($missing)) {
    echo json_encode([
        'success' => false, 
        'error' => 'Missing required fields: ' . implode(', ', $missing),
        'received' => $data // This helps you debug in the "Response" tab
    ]);
    exit;
}

try {
    // 1. Insert order — Your trigger 'trg_Order' handles the ID via seq_Order
    // Note: status is set to 'Pending'
    $sql  = "INSERT INTO HUDDER_ORDER (ORDER_DATE, ORDER_TIME, STATUS, USER_ID, SLOT_ID)
             VALUES (SYSDATE, TO_CHAR(SYSDATE,'HH12:MI AM'), 'Pending', :user_id, :slot_id)";
    
    $stmt = oci_parse($conn, $sql);
    if (!$stmt) {
        $e = oci_error($conn);
        throw new Exception('Order Prep Error: ' . $e['message']);
    }

    oci_bind_by_name($stmt, ':user_id', $user_id);
    oci_bind_by_name($stmt, ':slot_id', $slot_id);
    
    $r = oci_execute($stmt, OCI_NO_AUTO_COMMIT);
    if (!$r) {
        $e = oci_error($stmt);
        throw new Exception('Order Exec Error: ' . $e['message']);
    }

    // 2. Retrieve the Order ID just generated by the sequence/trigger
    $idq = oci_parse($conn, "SELECT seq_Order.CURRVAL AS new_id FROM DUAL");
    oci_execute($idq);
    $idrow    = oci_fetch_assoc($idq);
    $order_id = $idrow['NEW_ID'];

    if (!$order_id) {
        throw new Exception('Could not retrieve new order_id from database');
    }

    // 3. Insert into ORDER_PRODUCT table
    $sql2  = "INSERT INTO ORDER_PRODUCT (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
              VALUES (:order_id, :product_id, :quantity, :unit_price)";
    
    $stmt2 = oci_parse($conn, $sql2);
    if (!$stmt2) {
        $e = oci_error($conn);
        throw new Exception('Order Product Prep Error: ' . $e['message']);
    }

    oci_bind_by_name($stmt2, ':order_id',   $order_id);
    oci_bind_by_name($stmt2, ':product_id', $product_id);
    oci_bind_by_name($stmt2, ':quantity',   $quantity);
    oci_bind_by_name($stmt2, ':unit_price', $unit_price);
    
    $r2 = oci_execute($stmt2, OCI_NO_AUTO_COMMIT);
    if (!$r2) {
        $e = oci_error($stmt2);
        throw new Exception('Order Product Exec Error: ' . $e['message']);
    }

    // 4. Finalize the transaction
    $committed = oci_commit($conn);
    if (!$committed) {
        $e = oci_error($conn);
        throw new Exception('Database Commit failed: ' . $e['message']);
    }

    // 5. Store order details in session for the Payment/Receipt page
    $_SESSION['pending_order'] = [
        'order_id'   => $order_id,
        'user_id'    => $user_id,
        'product_id' => $product_id,
        'quantity'   => $quantity,
        'slot_id'    => $slot_id,
        'amount'     => $amount,
    ];

    echo json_encode([
        'success' => true, 
        'order_id' => $order_id, 
        'amount' => $amount,
        'message' => 'Order created successfully'
    ]);

} catch (Exception $e) {
    oci_rollback($conn); // Undo everything if any part fails
    error_log('[create-order] CRITICAL ERROR: ' . $e->getMessage());
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
}
?>